const http = require('http');
const https = require('https');
const fs = require('fs');
const path = require('path');
const url = require('url');
const PORT = process.env.PORT || 3000;
const BM_KEY = 'MzkyZTM0ZjZlYjUxNmMyOTI3NjMwMjpCTVQtYTY4NjIyM2FiOTU4MjViMDhlZGZlODY1ODg0ZjIwZGMxNzU4Y2QzZg==';
function httpsGet(hostname,p,headers){return new Promise((res,rej)=>{const req=https.request({hostname,path:p,method:'GET',headers:{'User-Agent':'CDK/1.0',...headers}},r=>{let b='';r.on('data',c=>b+=c);r.on('end',()=>res({status:r.statusCode,body:b}));});req.on('error',rej);req.setTimeout(12000,()=>{req.destroy();rej(new Error('Timeout'));});req.end();});}
function jsend(res,status,obj){res.writeHead(status,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*'});res.end(JSON.stringify(obj));}
function extractPrice(item){if(!item)return null;if(item.price!==undefined&&typeof item.price!=='object')return parseFloat(item.price);if(item.price&&item.price.amount!==undefined)return parseFloat(item.price.amount);if(item.listing&&item.listing.price&&item.listing.price.amount!==undefined)return parseFloat(item.listing.price.amount);if(item.unit_price!==undefined)return parseFloat(item.unit_price);if(item.listing_price!==undefined)return parseFloat(item.listing_price);return null;}
function extractGrade(item){if(!item)return '';if(item.grade&&item.grade.name)return item.grade.name;if(item.listing&&item.listing.grade&&item.listing.grade.name)return item.listing.grade.name;if(item.condition)return item.condition;if(item.quality)return item.quality;return '';}
function gradeOrder(g){const n=(g||'').toLowerCase();if(n.includes('new')||n.includes('neuf')||n.includes('parfait'))return 1;if(n.includes('good')||n.includes('bon')||n.includes('tr'))return 2;if(n.includes('fair')||n.includes('correct'))return 3;return 4;}
async function searchListings(query,res){const bmPath='/ws/listings?q='+encodeURIComponent(query)+'&page_size=20';try{const r=await httpsGet('www.backmarket.fr',bmPath,{'Authorization':'Basic '+BM_KEY,'Accept':'application/json','Accept-Language':'en-gb'});let parsed;try{parsed=JSON.parse(r.body);}catch(e){return jsend(res,502,{error:'Invalid JSON. Status:'+r.status});}if(r.status!==200){const msg=(parsed.error&&(parsed.error.message||parsed.error.code))||('Status '+r.status);return jsend(res,r.status,{error:msg});}let raw=[];if(Array.isArray(parsed))raw=parsed;else if(Array.isArray(parsed.results))raw=parsed.results;else if(Array.isArray(parsed.listings))raw=parsed.listings;const items=raw.map(item=>({title:item.title||item.name||item.product_title||item.displayTitle||item.label||'Listing',price:extractPrice(item),grade:extractGrade(item),currency:(item.price&&item.price.currency)||(item.listing&&item.listing.price&&item.listing.price.currency)||'EUR'})).filter(i=>i.price!==null&&!isNaN(i.price)&&i.price>0).sort((a,b)=>gradeOrder(a.grade)-gradeOrder(b.grade)||a.price-b.price);jsend(res,200,{count:items.length,results:items});}catch(e){jsend(res,502,{error:'Cannot reach BackMarket: '+e.message});}}
async function exchangeRate(res){try{const r=await httpsGet('api.exchangerate-api.com','/v4/latest/USD',{Accept:'application/json'});const d=JSON.parse(r.body);jsend(res,200,{rate:d.rates.EUR,base:'USD',target:'EUR'});}catch(e){jsend(res,502,{error:'Exchange rate unavailable'});}}
const MIME={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'application/javascript','.json':'application/json'};
function serveFile(reqPath,res){const fp=path.join(__dirname,'public',reqPath==='/'?'index.html':reqPath);fs.readFile(fp,(err,content)=>{if(err){res.writeHead(404);return res.end('Not found');}res.writeHead(200,{'Content-Type':MIME[path.extname(fp)]||'text/plain'});res.end(content);});}
http.createServer((req,res)=>{const parsed=url.parse(req.url,true);const p=parsed.pathname;if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*'});return res.end();}if(p==='/api/search'){const q=(parsed.query.q||'').trim();return q?searchListings(q,res):jsend(res,400,{error:'Missing ?q='});}if(p==='/api/rate')return exchangeRate(res);serveFile(p,res);}).listen(PORT,'0.0.0.0',()=>console.log('CDK Calculator on port '+PORT));